### ISSUE TITLE
bug in >1.8.1 re calling a template

### ISSUE THREAD

**Issue by menagerie198** [SilentVoid13/Templater#381]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: >1.8.1
 - Obsidian version: 0.12.16
 - Templater settings: Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command) Templates/2_time_now_TP, `## <% tp.date.now("HHmm") %> – `]

**Describe the bug**
I have this Template attached to a hotkey (using the 'Hotkeys for Templates' plugin - Alt+T). It has stopped working in the last 24 hours (>v1.8.1). A '+' symbol replaces the cursor when I press Alt. I can still call the Template from the Command Pallet. Changing the hotkey does not call the Template. All other Templates and hotkeys work.

**Expected behavior**
Alt+T calls and renders an H2 with the current time.

**Screenshots**

**Additional context**
Updating this morning to v1.9.2 brought about the bug - reverting back to 1.8.1 brought the functionality back.

**Comment by JeppeKlitgaard** [comment]
I believe you will find a `this.templaterPlugin.templater.append_template is not a function` error in the console.

I think this error comes from the `append_template` having changed name during a refactor. This should probably be filed as a bug with `Hotkeys For Templates` plugin, not `Templater` itself.

**Comment by SilentVoid13** [comment]
Hey @menagerie198 this is a bug on the 'Hotkeys for templates' plugin side, well it's kinda my fault too.
I refactored a big part of Templater's for 1.9.x and renamed a lot of functions / methods.
'Hotkeys for templates' tries to use the old functions name, that do not exist anymore.

I'm thinking about exposing a standard Templater API that I will try to keep stable (like Dataview for example) to prevent this type of errors in the future.

However, Templater 1.9.x introduced the hotkeys for templates functionality too, check the settings if you want to bind a hotkey for a template.

**Comment by menagerie198** [comment]
Thanks for this... I updated `Templater` and disabled `Hotkeys for Templates`. All is well - Love the `hotkey` function! Also posted a bug report on the `Hotkeys for Templates` git.
